// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXSWYey6VEwH2k2hXnRMpI-oHhnemoCfM',
    appId: '1:1055390270264:web:28aca453fb86c445bdb7cd',
    messagingSenderId: '1055390270264',
    projectId: 'test-68588',
    authDomain: 'test-68588.firebaseapp.com',
    storageBucket: 'test-68588.firebasestorage.app',
    measurementId: 'G-DPG68TKE2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8a5GIdFNAOdI707N9Cb0P3eYEuJv70Y',
    appId: '1:1055390270264:android:eba865e1677377b1bdb7cd',
    messagingSenderId: '1055390270264',
    projectId: 'test-68588',
    storageBucket: 'test-68588.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1u6x5tDNWDdKjJC583WSXjhl9XqbdGy4',
    appId: '1:1055390270264:ios:ced44c2e35fc8613bdb7cd',
    messagingSenderId: '1055390270264',
    projectId: 'test-68588',
    storageBucket: 'test-68588.firebasestorage.app',
    iosBundleId: 'com.example.tugasAwesomeNotification',
  );
}
